kids/urls.py
from django.urls import path
from .views import *

app_name = 'kids'
urlpatterns = [
    path('cold/', cold, name='cold'),
    path('cold/advices', cold_advices, name='cold_advices')
]

minor_aliments/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kids/', include('kids.urls', namespace='kids')),
]

kids/models.py
from django.db import models

# Create your models here.

kids/forms.py
from django import forms


class ColdForm(forms.Form):
    until_3_month = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                           choices=((False, 'خیر'), (True, 'بله')),
                                           label='آیا کودک شما زیر ۳ ماه است',
                                           widget=forms.Select(attrs={'class': 'form-select'}))
    fever = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                   choices=((False, 'خیر'), (True, 'بله')),
                                   label='آیا کودک شما تبی بیش از ۳۸/۵ درجه سانتی گراد دهانی یا ۳۹ درجه سانتی گراد مقعدی دارد',
                                   widget=forms.Select(attrs={'class': 'form-select'}))
    ailment = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                     choices=((False, 'خیر'), (True, 'بله')),
                                     label='آیا کودک به شدت احساس ناخوشی می کند',
                                     widget=forms.Select(attrs={'class': 'form-select'}))
    breath = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                    choices=((False, 'خیر'), (True, 'بله')),
                                    label='آیا کودک شما در تنفس مشکل دارد',
                                    widget=forms.Select(attrs={'class': 'form-select'}))
    swallow = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                     choices=((False, 'خیر'), (True, 'بله')),
                                     label='آیا کودک شما در بلع مشکل شدید دارد',
                                     widget=forms.Select(attrs={'class': 'form-select'}))
    fever_3_days = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                          choices=((False, 'خیر'), (True, 'بله')),
                                          label='آیا تب بیش از ۳۷/۵ درجه سانتی گراد دهانی یا ۳۸ درجه سانتی گراد مقعدی بیش از ۳ روز وجود دارد',
                                          widget=forms.Select(attrs={'class': 'form-select'}))
    liquids = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                     choices=((False, 'خیر'), (True, 'بله')),
                                     label='آیا کودک به خوبی مایعات نمی نوشد',
                                     widget=forms.Select(attrs={'class': 'form-select'}))
    discharge = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                       choices=((False, 'خیر'), (True, 'بله')),
                                       label='آیا ترشح بینی پیوسته سبز رنگ است',
                                       widget=forms.Select(attrs={'class': 'form-select'}))
    sputum = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                    choices=((False, 'خیر'), (True, 'بله')),
                                    label='آیا کودک خلط سبز رنگ دارد',
                                    widget=forms.Select(attrs={'class': 'form-select'}))

kids/views.py
from django.contrib import messages
from django.shortcuts import render

from kids.forms import ColdForm


def cold(request):
    if request.method == 'POST':
        form = ColdForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if data['until_3_month'] or data['fever'] or data['ailment'] \
                    or data['breath'] or data['swallow']:
                messages.info(request,
                              'در صورت لزوم از داروی ضد تب استفاده کنید و هم اکنون به مرکز بهداشتی درمانی مراجعه کنید',
                              'info')
            elif data['fever_3_days'] or data['liquids'] or data['discharge'] or data['sputum']:
                messages.info(request, 'به مرکز بهداشتی درمانی مراجعه کنید', 'info')
            else:
                messages.info(request, '<a href="/kids/cold/advices">توصیه های خانگی</a> را مطالعه کنید.', 'info')
    else:
        form = ColdForm()
    return render(request, 'kids/cold.html', {'form': form})


def cold_advices(request):
    return render(request, 'kids/cold_advices.html')

kids/templates/kids/cold.html
{% extends 'base.html' %}


{% block title %}
    سرماخوردگی | ناخوشی های کودکان
{% endblock %}

{% block content %}
    {% include 'kids/includes/navbar.html' %}

    <section style="background-color: #eee;">
        <div class="container">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-md-6">
                    <div class="card text-black mb-5 mt-2" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">سرماخوردگی</p>
                                {% include 'kids/includes/message.html' %}

                                <form method="post" class="mx-1 mx-md-4" novalidate>
                                    {% csrf_token %}
                                    {{ form.as_p }}

                                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4 mt-2">
                                        <button type="submit" class="btn btn-primary btn-lg">بررسی</button>
                                    </div>

                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

kids/templates/kids/cold_advices.html
{% extends 'base.html' %}


{% block title %}
    سرماخوردگی | توصیه های خانگی
{% endblock %}


{% block content %}
    {% include 'kids/includes/navbar.html' %}

    <section style="background-color: #eee;">
        <div class="container">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-md-12">
                    <div class="card text-black mb-5 mt-2" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">توصیه های خانگی - سرماخوردگی</p>

                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
                                    به یاد داشته باشید سرماخوردگی نیاز به درمان آنتی بیوتیکی ندارد. آنتی بیوتیک‌ها دوره سرماخوردگی را کوتاه و آن را درمان نمی کنند.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
                                    1. اگر کودک تب دارد به بخش تب مراجعه کنید.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
                                    2. برای رفع تب و ناراحتی، استامینوفن یا بروفن به کودک بدهید. به هیچ بیمار زیر 20 سالی که بیماری ویروسی دارد نباید آسپرین داد.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
                                    3. برای آبریزش بینی، اگر کودکتان می تواند تشویقش کنید که فین کند. به او نگویید دماغش را بالا نکشد. این کار در واقع راه خوبی برای تمیز کردن مجرای بینی است و باعث می شود عفونت به گوش یا سینوس‌ها گسترش نیابد. در کودکان کوچکی که نمی توانند فین کنند و بینی شان را تمیز کنند، افشانه آب نمک (سالین) بینی که از داروخانه قابل خرید است، می تواند به تمیز کردن بینی کمک کند. از افشانه های ضد احتقان بینی برای کودکان استفاده نکنید.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
4. برای رفع انسداد بینی، در حالی که کودک به پشت خوابیده، 3 قطره آب گرم در هر یک از سوراخ های بینی بریزید. پس از 1 دقیقه، از کودک بخواهید فین کند. هر اندازه که لازم می دانید می توانید این کار را تکرار کنید.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
5. داروهای ضد احتقان خوراکی یا ترکیبی، مثل دیفن هیدرامین کامپاند، می توانند به خشک شدن آبریزش بینی و بهبود خواب کمک کنند. البته به یاد داشته باشید اگر بیماری قلبی، پرفشاری خون بالای کنترل نشده یا آسم شدید وجود دارد، نباید از داروهای ضد احتقان استفاده کرد. داروهای آنتی هیستامین برای کودکان زیر 2 سال توصیه نمی شوند.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
6. اگر به خواب رفتن یا تمرکز کودک در مدرسه با مشکل مواجه است می توان از شربت های ضد سرفه حاوی دکسترومتورفان کمک گرفت. نباید سرفه خلط دار یا مرطوب را سرکوب کرد زیرا این نوع سرفه اخلاط سینه را پاک می کند. اگر کودک مشکلات تنفسی دارد (مثل آسم) نباید دکسترومتورفان به وی داد. به کودکان کمتر از یک سال به هیچ وجه دکسترومتورفان ندهید.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
7. خوردن چند جرعه مایعات گرم به آرام شدن سرفه کمک می کند. آب گرم با شکر یا آب میوه گرم مثل شربت لیمو یا سوپ جوجه گزینه های خوبی هستند.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
8. قرص های مکیدنی در کودکان بالای 2 سال که امکان مکیدن دارند، می تواند به رفع خشکی و سوزش گلو کمک کند مشروط بر اینکه کودک بتواند یک آبنبات سفت را بمکد.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
9. نگذارید کودک در معرض دود سیگار قرار بگیرد.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
10. کودک نباید ورزش و بازی کند و باید به خوبی استراحت کند. به کودک مایعات اضافی بدهید. اگر دستگاه بخور سرد دارید، از آن استفاده کنید.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
11. اگر کودکتان شیرخوار است، شیردهی را قطع نکنید. ممکن است لازم شود دفعات تغذیه را افزایش دهید.
                                </p>
                                <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
12. شستن دست‌ها می تواند از گسترش عفونت پیشگیری کند.
                                </p>

                                {% for advice in advices %}
                                    <p class="text-right h5 mb-2 mx-1 mx-md-4 mt-4">
                                        {{ advice }}
                                    </p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

kids/templates/kids/includes/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {% autoescape off %}
                {{ message }}
            {% endautoescape %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

kids/templates/kids/includes/navbar.html
<style>
    .dropdown-menu li {
        position: relative;
    }

    .dropdown-menu .dropdown-submenu {
        display: none;
        position: absolute;
        right: 100%;
        top: -7px;
    }

    .dropdown-menu .dropdown-submenu-left {
        left: 100%;
        right: auto;
    }

    .dropdown-menu > li:hover > .dropdown-submenu {
        display: block;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ناخوشی های جزئی</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">صفحه اصلی</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        کودکان
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="#">
                                سرماخوردگی &raquo;
                            </a>
                            <ul class="dropdown-menu dropdown-submenu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'kids:cold' %}">سرماخوردگی</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'kids:cold_advices' %}">توصیه های خانگی</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                </li>
        </div>
    </div>
</nav>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block header_reference %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    {% endblock %}
</head>
<body>

{% block content %}
{% endblock %}

{% block footer_reference %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'navbar.js' %}"></script>
{% endblock %}

</body>
</html>